backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
  - name: projects
    label: Projects
    folder: content/projects 
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: postType, label: Post Type, widget: "hidden", default: "project" }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: collaborations, label: Collaborations, widget: list, required: false }
      - { name: website, label: Website, required: false, }
      - { name: color, label: Project Color }
      - { name: image, label: Feature Image, widget: image} 
      - { name: projectImage1, label: Project Image 1, required: false, widget: image}
      - { name: projectImage2, label: Project Image 2, required: false, widget: image}
      - { name: projectImage3, label: Project Image 3, required: false, widget: image}
      - { name: projectImage4, label: Project Image 4, required: false, widget: image}
      - { name: projectImage5, label: Project Image 5, required: false, widget: image}
      - { name: projectImage6, label: Project Image 6, required: false, widget: image} 
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: postType, label: Post Type, widget: "hidden", default: "blog" }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Feature Image, widget: image} 