backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
      - label: "Projects"
        name: "projects"
        file: "content/pages/projects.md"
        fields:
          - label: Websites 
            name: websites
            widget: list
            required: false
            fields:
              - { label: Thumbnail, name: image, widget: image, required: false }
              - { label: Name, name: name}
              - { label: Link, name: link}
          
  - name: projects
    label: Projects
    folder: content/projects 
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: type, label: Type, widget: hidden, default: project}
      - { name: description, label: Caption }
      - { name: body, label: Body, widget: markdown }
      - { name: collaborations, label: Collaborations, widget: list, required: false }
      - { name: website, label: Website, required: false}
      - { name: color, label: Project Color }
      - { name: homepage, label: Homepage Featured?, widget: select, options: ['False','True'], default: ['False']}
      - { name: featureImage, label: Feature Image, widget: image } 
      - { name: mobileFeature, label: Mobile Feature Image, required: false, widget: image } 
      - label: Gallery
        name: galleryImages
        widget: list
        required: false
        fields:
          - { label: Image, name: image, widget: image, required: false }
          - { label: Mobile Image, name: imageMobile, widget: image, required: false }
          - { label: Video URL, name: video, required: false}
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: type, label: Type, widget: hidden,default: blog}
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Feature Image, widget: image} 