backend:
  name: git-gateway
  branch: master
  
media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    folder: content/projects 
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Thumbnail, widget: image} 
  - name: Pages
    label: Pages
    folder: content/pages 
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Thumbnail, widget: image} 
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Thumbnail, widget: image} 